versions.v1 = {
  name: "Cobw",
  version: "1",
  date: "2025",
  folder: "asset-v1/",
  looptime: 10940,
  bpm: 88,
  totalframe: 494,
  nbpolo: 7,
  bonusloopA: false,
  bonusendloopA: true,
  colBck: "#0F0F0F",
  col0: "#919191",
  col1: "#5f5f5f",
  col2: "#4b4b4b",
  col3: "#373737",
  col4: "#232323",
  animearray: [
    {
      name: "01_Thumpw",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "02_Knurk",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "03_Cobw",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "06_Drick",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
    {
      name: "temp_polo",
      color: "7D7D7D",
      uniqsnd: !0,
    },
  ],
  bonusarray: [
    {
      name: "blank",
      src: "b1-v1-blank-hb",
      code: "1,2,3,4,5",
      sound: "aspire-blank",
      aspire: "aspire-blank",
      loop: 1,
    },
  ],
};
